### PR TITLE
ESP8266: Fix example compilation error

### LINKED ISSUE #910: EnergyMeterPulseSensor example does not compile on 2.1.1 and 2.2.0-beta
```
Error: call of overloaded 'set(volatile long unsigned int&)' is ambiguous
send(wattMsg.set(watt)); \ Send watt value to gw
```

1. I thought Jenkins did compilation tests of all examples. Don't we do that? If not, would it be easy to do? If we do, how did this go unnoticed?
2. What would be the correct solution?

For more details see https://forum.mysensors.org/post/73888

### PR DESCRIPTION
**Pull request by tekka007**
- Fixes #910

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please

**Comment by tekka007** [comment]
Jenkins, build examples please
