### ISSUE TITLE
Debug prints portable commit causing build failure on Linux

### ISSUE THREAD

**Issue by madimadi** [mysensors/MySensors#955]
Hi,
[The commit: Make debug prints portable](https://github.com/mysensors/MySensors/commit/0ed558f1d077e68b69c2fe1cb0056c526ae3023e)
looks to be causes compiler failure.
`./core/MySensorsCore.cpp:172:2: error: expected ‘)’ before ‘PRIu8’` as an example for compile failure.
I guess `drivers/Linux/Arduino.h:#define PSTR(x) (x)` may need to be variadic macro.
@tekka007 and @henrikekblad, may I know your opinion?

**Comment by mfalkvidd** [comment]
I'm able to reproduce this error on Rasbpian Wheezy but not on Raspbian Stretch
Configure command: `./configure --extra-cxxflags="-DMY_DEBUG" && make`

Error on the following configuration:
```
gcc -v |& grep 'gcc version'
gcc version 4.7.2 (Debian 4.7.2-5+rpi1)
grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
```
No error, compile runs fine on the following configuration:
```
gcc -v |& grep 'gcc version'
gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1)
grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
```

**Comment by tekka007** [comment]
Also no error on this configuration:
```
gcc -v |& grep 'gcc version'
gcc version 4.9.2 (Raspbian 4.9.2-10)
grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
```

**Comment by mfalkvidd** [comment]
This works on Wheezy/ gcc 4.7.2:
`./configure --extra-cxxflags="-DMY_DEBUG -D__STDC_FORMAT_MACROS" && make`
